### ISSUE TITLE
Account suspended!

### ISSUE THREAD

**Issue by micahelsjr2000** [rossum01/win_2#1]
Thanks for sharing, Account is locked after a few minutes.

**Comment by rossum01** [comment]
Then? Who did the fault?. GitHub has guide you why ask me? Your fault. Don't want read and follow rules and only protest. Better ask to who suspend you account, not me.

**Comment by rossum01** [comment]
Then? Who did the fault?. GitHub has guide you why ask me? Your fault. Don't want read and follow rules and only protest. Better ask to who suspend you account, not me.
